server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://123.57.89.111:3306/web?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: web
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true